# Generated by Django 3.1.1 on 2020-09-28 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200926_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to='products_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 17, 1, 59, 473810), verbose_name='date added'),
        ),
    ]
